// <auto-generated />
using System;
using GrapheneTrace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrapheneTrace.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208210324_ClinicianPatientLinksFixed")]
    partial class ClinicianPatientLinksFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrapheneTrace.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Clinician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccessAllPatients")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialisation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clinicians");
                });

            modelBuilder.Entity("GrapheneTrace.Models.ClinicianPatient", b =>
                {
                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("ClinicianId", "PatientId");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicianPatients");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("GrapheneTrace.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Admin", b =>
                {
                    b.HasOne("GrapheneTrace.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("GrapheneTrace.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Clinician", b =>
                {
                    b.HasOne("GrapheneTrace.Models.User", "User")
                        .WithOne("ClinicianProfile")
                        .HasForeignKey("GrapheneTrace.Models.Clinician", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Models.ClinicianPatient", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Clinician", "Clinician")
                        .WithMany("PatientLinks")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Models.Patient", "Patient")
                        .WithMany("ClinicianLinks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Patient", b =>
                {
                    b.HasOne("GrapheneTrace.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("GrapheneTrace.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Clinician", b =>
                {
                    b.Navigation("PatientLinks");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Patient", b =>
                {
                    b.Navigation("ClinicianLinks");
                });

            modelBuilder.Entity("GrapheneTrace.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("ClinicianProfile");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
